algorithm: cgmatch
save_dir: ./saved_models/classic_cv_imb
save_name: cgmatch_cifar100_lb150_100_ulb300_100_0
resume: True
load_path: ./saved_models/classic_cv_imb/cgmatch_cifar100_lb150_100_ulb300_100_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 256
num_train_iter: 262144
num_eval_iter: 1024
warm_up_iter: 2048
num_log_iter: 256
queue_size: 1000
num_labels: 150
batch_size: 64
eval_batch_size: 25600
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
lambda_h: 1.0
uratio: 2
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False
data_dir: ./data
dataset: cifar100
train_sampler: RandomSampler
num_classes: 100
num_workers: 10
seed: 0
world_size: 1
rank: 0
distributed: False
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None
include_lb_to_ulb: False
lb_imb_ratio: 100
ulb_imb_ratio: 100
ulb_num_labels: 300
model_dir: ./training_dynamics/classic_cv_imb/cgmatch_cifar100_lb150_100_ulb300_100_0/
