algorithm: cgmatch
save_dir: ./saved_models/classic_cv
save_name: cgmatch_stl10_250_0
resume: True
load_path: ./saved_models/classic_cv/cgmatch_stl10_250_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 1024
num_train_iter: 1048576
num_eval_iter: 5120
warm_up_iter: 2048
num_log_iter: 256
queue_size: 1000
num_labels: 250
batch_size: 64
eval_batch_size: 12800
hard_label: True
T: 0.5
dist_align: True
dist_uniform: True
ema_p: 0.999
p_cutoff: 0.95
ulb_loss_ratio: 1.0
lambda_h: 1.0
uratio: 7
ema_m: 0.999
crop_ratio: 0.875
img_size: 96
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_var_37_2
net_from_name: False
data_dir: ./data
dataset: stl10
train_sampler: RandomSampler
num_classes: 10
num_workers: 16
seed: 0
world_size: 1
rank: 0
distributed: False
dist_url: tcp://127.0.0.1:10007
dist_backend: nccl
gpu: None
model_dir: ./training_dynamics/classic_cv/cgmatch_stl10_250_0/
